import { supabase } from '../../../lib/supabase';
import { db } from '../../../lib/db';
import { Question, Explanation } from '../types';

/**
 * Interface mapping the exact shape of a Question row in the Supabase 'questions' table.
 */
interface QuestionDBRow {
  /** The UUID generated by the database. */
  id: string;
  /** The business logic ID used in the app (e.g., "BIO1"). */
  v1_id: string;
  /** The subject of the question. */
  subject: string;
  /** The topic within the subject. */
  topic: string;
  /** The sub-topic within the topic. */
  subTopic: string;
  /** The name of the exam the question is from. */
  examName: string;
  /** The year of the exam. */
  examYear: number;
  /** The shift or date of the exam. */
  examDateShift: string;
  /** Difficulty level (Easy/Medium/Hard). */
  difficulty: string;
  /** Type of question (e.g., MCQ). */
  questionType: string;
  /** The question text (English). */
  question: string;
  /** The question text (Hindi). */
  question_hi: string;
  /** Array of option texts (English). */
  options: string[];
  /** Array of option texts (Hindi). */
  options_hi: string[];
  /** The correct answer text. */
  correct: string;
  /** Array of tag strings. */
  tags: string[];
  /** JSONB object containing the explanation. */
  explanation: Explanation;
  /** updated_at timestamp. */
  updated_at: string;
}

/**
 * Fetches lightweight metadata for all available questions.
 * Uses Delta Sync to only fetch modified rows.
 *
 * @param {function} [onProgress] - Optional callback to report download progress (fetched vs total).
 * @returns {Promise<Question[]>} A promise resolving to a list of Question objects (with empty content fields).
 */
export const fetchQuestionMetadata = async (
  onProgress?: (fetchedCount: number, totalCount: number) => void
): Promise<Question[]> => {
  let allRows: Partial<QuestionDBRow>[] = [];
  
  // 1. Get last sync timestamp
  const lastSync = await db.getSyncTimestamp('quiz_metadata_sync');

  // Get Total Count to enable progress tracking (for delta sync we just count what we need to fetch)
  let countQuery = supabase.from('questions').select('*', { count: 'exact', head: true });
  if (lastSync) {
      countQuery = countQuery.gt('updated_at', lastSync);
  }
  const { count, error: countError } = await countQuery;

  if (countError) {
      console.error('Error fetching count:', countError);
  }
  const totalRecords = count || 0;
  
  if (totalRecords > 0) {
      // 2. Fetch only changed records via RPC (or fallback)
      let from = 0;
      const limit = 1000;
      let hasMore = true;

      try {
        while (hasMore) {
          const { data, error } = await supabase
            .rpc('get_filtered_quiz_metadata', { p_last_sync_at: lastSync })
            .range(from, from + limit - 1);

          if (error) throw error;

          if (data && data.length > 0) {
            allRows = [...allRows, ...data];
            if (onProgress) onProgress(allRows.length, totalRecords);

            if (data.length < limit) hasMore = false;
            else from += limit;
          } else {
            hasMore = false;
          }
        }
      } catch (error) {
        console.error("Failed to fetch metadata:", error);
        throw error;
      }

      // Update sync timestamp
      const newSyncTimestamp = new Date().toISOString();
      await db.setSyncTimestamp('quiz_metadata_sync', newSyncTimestamp);
  }

  // Map the raw DB rows to the internal Question model structure.
  // Note: Content fields like 'question' and 'options' are left empty/default.
  const mappedRows = allRows.map((row) => ({
    id: row.id!,
    v1_id: row.v1_id || '',
    sourceInfo: {
      examName: row.examName || '',
      examYear: row.examYear || 0,
      examDateShift: row.examDateShift,
    },
    classification: {
      subject: row.subject || '',
      topic: row.topic || '',
      subTopic: row.subTopic,
    },
    tags: row.tags || [],
    properties: {
      difficulty: row.difficulty || 'Medium',
      questionType: row.questionType || 'MCQ',
    },
    // Placeholder values for non-metadata fields
    question: '',
    options: [],
    correct: '',
    explanation: {},
    updated_at: row.updated_at
  }));

  if (mappedRows.length > 0) {
      // Save mapped rows to IndexedDB
      await db.saveQuizMetadataCache(mappedRows);
  }

  // Return everything from cache to ensure we have the full set
  const cachedData = await db.getQuizMetadataCache();

  // Deduplicate by v1_id to ensure no duplicate questions in the UI
  const uniqueRows = Array.from(new Map(cachedData.map(item => [item.v1_id || item.id, item])).values());
  return uniqueRows;
};

export const fetchQuestionsByIds = async (ids: string[]): Promise<Question[]> => {
  if (ids.length === 0) return [];

  // Batch the requests to avoid URL length limits and improve performance for large sets
  const BATCH_SIZE = 200;
  const batches = [];
  for (let i = 0; i < ids.length; i += BATCH_SIZE) {
    batches.push(ids.slice(i, i + BATCH_SIZE));
  }

  let allData = [];

  try {
    const results = await Promise.all(
      batches.map(async (batchIds) => {
        const { data, error } = await supabase
          .from('questions')
          .select('*')
          .in('id', batchIds);

        if (error) throw error;
        return data;
      })
    );

    allData = results.flat();
  } catch (error) {
    console.error("Error fetching full questions:", error);
    throw error;
  }

  // Map the DB rows to the full Question model
  // Deduplicate full questions by v1_id in case there are still DB duplicates
  const uniqueFullQuestionsById = Array.from(new Map((allData as QuestionDBRow[]).map(item => [item.v1_id || item.id, item])).values());

  // Deep deduplication: Filter out questions that have the exact same text content
  // This catches database entry errors where the same question was uploaded twice with different IDs
  const seenContent = new Set<string>();
  const uniqueFullQuestions = uniqueFullQuestionsById.filter((q) => {
    // Normalize text: lowercase and remove all whitespace for robust comparison
    const normEn = (q.question || '').toLowerCase().replace(/\s+/g, '');
    const normHi = (q.question_hi || '').toLowerCase().replace(/\s+/g, '');

    // Create a unique composite key. If English is empty, rely on Hindi, and vice versa.
    const contentKey = `${normEn}-${normHi}`;

    if (!contentKey || contentKey === '-') {
       // Fallback if question text is completely missing, don't deduplicate here
       return true;
    }

    if (seenContent.has(contentKey)) {
      return false; // Duplicate content found, discard
    }

    seenContent.add(contentKey);
    return true;
  });

  return uniqueFullQuestions.map((row) => ({
    id: row.id,
    v1_id: row.v1_id,
    sourceInfo: {
      examName: row.examName,
      examYear: row.examYear,
      examDateShift: row.examDateShift,
    },
    classification: {
      subject: row.subject,
      topic: row.topic,
      subTopic: row.subTopic,
    },
    tags: row.tags || [],
    properties: {
      difficulty: row.difficulty,
      questionType: row.questionType,
    },
    question: row.question,
    question_hi: row.question_hi,
    options: row.options,
    options_hi: row.options_hi,
    correct: row.correct,
    explanation: row.explanation,
  }));
};
